# Jekyll config Page
# Main Page
title: Felipe Desiglo Ferrare
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Felipe Desiglo Ferrare - M.Sc. - Software engineer and Philosopher, CTAL-Full (TA/TM/TTA), CTFL-AT, ITILv3, PSM I
jobTitle: Software Developer
Contry: BR
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://felipe84841.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  felipe84841
orcid_ID: 0000-0003-3896-8650
lattes_CV: 6035797505367483
linkedin_username:
    name: felipedesigloferrare
    pt-br: felipedesigloferrare
    en: felipedesigloferrare/en
google_analytics: UA-97857864-1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
